version: '3'
services:
 selenoid:
   network_mode: bridge
   image: aerokube/selenoid:latest
   volumes:
     - "/docker:/etc/selenoid"
     - "/var/run/docker.sock:/var/run/docker.sock"
     - "/docker/video:/opt/selenoid/video"
	 - "/logs:/opt/selenoid/logs"
  environment:
     - OVERRIDE_VIDEO_OUTPUT_DIR=/docker/video
     - TZ=America/Denver
   command: ["-conf", "/etc/selenoid/browsers.json", "-video-output-dir", "/opt/selenoid/video", "-log-output-dir", "/opt/selenoid/logs"]
   ports:
     - "4444:4444"

 selenoid-ui:
   image: "aerokube/selenoid-ui"
   network_mode: bridge
   links:
     - selenoid
   ports:
     - "8090:8080"
   command: ["--selenoid-uri", "http://selenoid:4444"]
